[fix] Extract dependencies from object reference instead of class (#13)
### Summary
From [here](https://github.com/chanzuckerberg/redis-memo/blob/main/lib/redis_memo/memoize_method.rb#L82), the object reference is used to call the dependency block, not the class. Fix extracting dependencies when calling `dependency_of` to use the object reference as well.

### Testing
Added specs to cover scenario. Without this change, the specs fail with something like
```
     Failure/Error: depends_on RedisMemo::Memoizable.new(id: obj.id, val: x)

     NoMethodError:
       undefined method `id' for #<Class:0x000056241936d420>
```

Specs succeed with this change